### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'channel')

### ISSUE THREAD

**Issue by lisabecker** [zwacky/goodreads-profile-workflow#8]
Hi Simon,

Very cool idea with the Goodreads workflow! Thank you for your work there.

I wanted to use it to spice up my own GitHub README but experienced the following error when running the job manually:

`TypeError: Cannot read properties of undefined (reading 'channel')`

Screenshot from GitHub Actions:
![image](https://github.com/zwacky/goodreads-profile-workflow/assets/39185499/2c685d2f-63a9-46a8-8e74-96265d72e64a)

This is my workflow in `.github/workflows/goodreads-profile-workflow.yml`:

```
name: Latest book list from a goodreads
on:
  schedule:
    - cron: "* * * * 1"
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with what you're currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@v1.2.3
        with:
          goodreads_user_id: "89343805"
          shelf: "currently-reading"
```

These are my lines in my README.md file:
```
<h3>📚 Books I'm currently reading:</h3>
<!-- GOODREADS-LIST:START -->
<!-- GOODREADS-LIST:END -->
```

My Goodreads ID is correct. Maybe it has something to do with my profile settings on Goodreads?

Thank you in advance for any pointers on how to getting it to run! :)
