### ISSUE TITLE
Intermittent "Error: TypeError: Cannot read properties of undefined (reading 'channel')"

### ISSUE THREAD

**Issue by JakeSteam** [zwacky/goodreads-profile-workflow#9]
Hey! I've been using the action for a while with no problems, but have had an issue in the last couple of days.

I suspect it isn't this action's fault, but instability in Goodreads' RSS feed. Still, reporting it here in case the handling can be improved. Sporadically, a task will fail with a `TypeError`:

```
Error: TypeError: Cannot read properties of undefined (reading 'channel')
````

Looking at the [code](https://github.com/zwacky/goodreads-profile-workflow/blob/main/index.js#L32), I'm guessing it's because the `channel` in `data.rss` doesn't exist, fetched [from this URL](https://www.goodreads.com/review/list_rss/29398258?shelf=currently-reading):
```
      if (!data.rss.channel.item) {
        return;
      }
      const items = Array.isArray(data.rss.channel.item)
        ? data.rss.channel.item
        : [data.rss.channel.item];
```

An [example failed run is here](https://github.com/JakeSteam/JakeSteam/actions/runs/8579174378/job/23513852601), note the seemingly [random past failures](https://github.com/JakeSteam/JakeSteam/actions).

I'm using this config in [my workflow](https://github.com/JakeSteam/JakeSteam/blob/main/.github/workflows/readme-update.yml):

```
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "29398258"
          template: "- [$title]($url) by $author (⭐️$average_rating)"
          sort_by_fields: "<user_date_added"
```

*Note: This is different to #8, as it is intermittent & my profile is public.*

**Comment by lancefrench** [comment]
Sometimes the call to Goodreads is going to fail completely, but sometimes they will successfully return an http response with a non-rss feed page saying something like "Sorry, not available right now."  In these cases, we will need error handling around the [feed parsing](https://github.com/zwacky/goodreads-profile-workflow/blob/a1b8b48b991987cb356422d51fcc91a81a2b6e26/index.js#L85).

**Comment by JakeSteam** [comment]
This seems fixed by #11, haven't had any issues since it was merged! 🎉

**Comment by RCheesley** [comment]
Sorry to bump an old closed issue, but I'm getting this on every run at the moment :( 

Any ideas?

**Comment by JakeSteam** [comment]
@RCheesley [My run from 5 hrs ago](https://github.com/JakeSteam/JakeSteam/actions/runs/10419590093) (and all in the last couple of months) seem fine, so I think the workflow is OK.

Try checking your `.yml` file looks [like mine](https://github.com/JakeSteam/JakeSteam/blob/main/.github/workflows/readme-update.yml), if it still doesn't work your Goodreads profile might not be public (as in #8):
```
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "29398258"
          template: "- [$title]($url) by $author (⭐️$average_rating)"
          sort_by_fields: "<user_date_added"
```
